laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'NovaHomeController@index')->name('novahome');

    Route::group([
        'prefix' => '2020_acesso_BJW'
    ], function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('filtro/{pais}', 'FiltroController@index')->name('filtro');
        Route::get('expositores/{pais}', 'FiltroController@getExpositores')->name('getExpositores');
        Route::get('expositor/{slug}', 'ExpositoresController@index')->name('expositores');
        Route::get('agenda', 'AgendaController@index')->name('agenda');
        // USER EVENTO
        Route::get('assine-livro/{user}', 'AssineLivroController@index')->name('assine-livro');
        Route::post('assine-livro/{user}', 'AssineLivroController@post')->name('assine-livro.post');
        Route::get('favoritas/{user}', 'CadastrosFavoritasController@index')->name('favoritas');
        Route::post('favoritas/{user}/{joia}', 'CadastrosFavoritasController@favoritar')->name('favoritas.post');
        Route::delete('favoritas/{user}/{joia}', 'CadastrosFavoritasController@desfavoritar')->name('favoritas.delete');
        Route::get('ebook/download/{user}', 'HomeController@download')->name('ebook.download');
        Route::get('palestra/zoom/{user}/{palestra}', 'AgendaController@relatorio')->name('relatorio.zoom');
        Route::get('compartilhar/whatsapp/{user}/{joia}', 'CadastrosFavoritasController@relatorioWhatsapp')->name('relatorio.whatsapp.compartilhar');
        Route::get('compartilhar/facebook/{user}/{joia}', 'CadastrosFavoritasController@relatorioFacebook')->name('relatorio.facebook.compartilhar');
        Route::get('compartilhar/email/{user}/{joia}', 'CadastrosFavoritasController@relatorioEmail')->name('relatorio.email.compartilhar');
    });

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Login Evento
    Route::group([
        'prefix' => 'evento',
        'namespace' => 'Evento',
    ], function () {
        Route::post('login', 'Auth\AuthController@login')->name('evento.login.post');
        Route::post('cadastro', 'Auth\AuthController@create')->name('evento.register.post');
        Route::post('atualizar/{user}', 'Auth\AuthController@update')->name('evento.atualizar.user');
        Route::post('esqueci-minha-senha', 'Auth\PasswordController@sendResetLinkEmail')->name('evento.password-request.post');
        Route::get('redefinicao-de-senha/{token}', 'Auth\PasswordController@showResetForm')->name('evento.password-reset');
        Route::post('redefinicao-de-senha', 'Auth\PasswordController@reset')->name('evento.password-reset.post');
        Route::get('logout', 'Auth\AuthController@logout')->name('evento.logout');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('evento', 'EventoController', ['only' => ['index', 'update']]);
        Route::resource('agenda', 'AgendaController', ['except' => 'show']);
        Route::resource('agenda.palestras', 'AgendaPalestrasController');
        Route::resource('assinaturas-livro', 'AssinaturasLivroController', ['only' => ['index', 'destroy']]);
        Route::resource('expositores-coletivos', 'ExpositoresColetivosController');
        Route::resource('expositores-coletivos.imagens', 'ExpositoresColetivosImagensController');
        Route::resource('expositores-individuais', 'ExpositoresIndividuaisController');
        Route::resource('expositores-individuais.joias', 'ExpositoresIndividuaisJoiasController');
        Route::resource('expositores-individuais.processo', 'ExpositoresIndividuaisProcessoController');
        Route::resource('expositores-individuais.campanha', 'ExpositoresIndividuaisCampanhaController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
        Route::get('cadastros', 'CadastrosController@index')->name('painel.cadastros.index');
        Route::get('relatorios/download-ebook', 'RelatoriosController@downloadEbook')->name('painel.relatorios.download-ebook');
        Route::get('relatorios/palestra-zoom', 'RelatoriosController@palestraZoom')->name('painel.relatorios.palestra-zoom');
        Route::get('relatorios/compartilhar-joia', 'RelatoriosController@compartilharJoia')->name('painel.relatorios.compartilhar-joia');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/ExpositoresIndividuaisController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ExpositoresIndividuaisRequest;
use App\Models\ExpositorIndividual;
use App\Models\Pais;

class ExpositoresIndividuaisController extends Controller
{
    public function index()
    {
        $registros = ExpositorIndividual::orderBy('nome', 'ASC')->get();

        return view('painel.expositores-individuais.index', compact('registros'));
    }

    public function create()
    {
        $paises = Pais::orderBy('nome', 'asc')->get();

        return view('painel.expositores-individuais.create', compact('paises'));
    }

    public function store(ExpositoresIndividuaisRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = ExpositorIndividual::upload_capa();
            if (isset($input['foto'])) $input['foto'] = ExpositorIndividual::upload_foto();

            ExpositorIndividual::create($input);

            return redirect()->route('painel.expositores-individuais.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function show(ExpositorIndividual $registro)
    {
        $paises = Pais::orderBy('nome', 'asc')->get();
        // $registro = ExpositorIndividual::find($registro);

        return view('painel.expositores-individuais.show', compact('registro', 'paises'));
    }

    public function edit(ExpositorIndividual $registro)
    {
        $paises = Pais::orderBy('nome', 'asc')->get();
        // $registro = ExpositorIndividual::find($registro);

        return view('painel.expositores-individuais.edit', compact('registro', 'paises'));
    }

    public function update(ExpositoresIndividuaisRequest $request, ExpositorIndividual $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = ExpositorIndividual::upload_capa();
            if (isset($input['foto'])) $input['foto'] = ExpositorIndividual::upload_foto();

            $registro->update($input);

            return redirect()->route('painel.expositores-individuais.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(ExpositorIndividual $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.expositores-individuais.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/expositores-individuais/processo/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>{{ $registro->nome }} /</small> Adicionar Processo</h2>
</legend>

{!! Form::model($registro, [
'route' => ['painel.expositores-individuais.processo.store', $registro->id],
'method' => 'post',
'files' => true])
!!}

@include('painel.expositores-individuais.processo.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/expositores-individuais/processo/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>{{ $registro->nome }} /</small> Editar Processo</h2>
    </legend>

    {!! Form::model($processo, [
        'route'  => ['painel.expositores-individuais.processo.update', $registro->id, $processo->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.expositores-individuais.processo.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/expositores-individuais/processo/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('video', 'Vídeo (Opcional)') !!}
    {!! Form::text('video', null, ['class' => 'form-control']) !!}
    <p class="alerta-quantidade">Incluir somente o ID do vídeo (Exemplo: https://vimeo.com/<strong>218983866</strong>)</p>
</div>

<div class="well form-group">
    {!! Form::label('imagem1', 'Imagem 1 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/expositores-individuais/processo/'.$processo->imagem1) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem1', ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem2', 'Imagem 2 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/expositores-individuais/processo/'.$processo->imagem2) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem2', ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem3', 'Imagem 3 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/expositores-individuais/processo/'.$processo->imagem3) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem3', ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

laravel/resources/views/painel/expositores-individuais/processo/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        {{ $registro->nome }} | Processo
        @if(empty($processo))
        <a href="{{ route('painel.expositores-individuais.processo.create', $registro->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Processo</a>
        @endif
    </h2>
    <p class="alerta-quantidade">Podem ser adicionadas até 3 imagens e 1 vídeo</p>
</legend>

@if(empty($processo))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>

@else
<div class="processo">
    <h4 class="titulo">Vídeo:</h4>
    @if ($processo->video)
    <p class="paragrafo">{{ $processo->video }}</p>
    @else
    <p class="paragrafo">Sem vídeo</p>
    @endif

    <hr>

    <h4 class="titulo">Imagens:</h4>
    @if ($processo->imagem1)
    <img src="{{ asset('assets/img/expositores-individuais/processo/'.$processo->imagem1) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if ($processo->imagem2)
    <img src="{{ asset('assets/img/expositores-individuais/processo/'.$processo->imagem2) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if ($processo->imagem3)
    <img src="{{ asset('assets/img/expositores-individuais/processo/'.$processo->imagem3) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if(!$processo->imagem1 && !$processo->imagem2 && !$processo->imagem3)
    <p class="paragrafo">Sem imagens</p>
    <hr>
    @endif
</div>

{!! Form::open([
'route' => ['painel.expositores-individuais.processo.destroy', $registro->id, $processo->id],
'method' => 'delete'
]) !!}

<button type="submit" class="btn btn-danger btn-sm btn-delete" style="margin-right:10px;"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

<a href="{{ route('painel.expositores-individuais.processo.edit', [$registro->id, $processo->id] ) }}" class="btn btn-primary btn-sm pull-left" style="margin-right:10px;">
    <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
</a>

@endif

<a href="{{ route('painel.expositores-individuais.index') }}" class="btn btn-default btn-sm btn-voltar"><span class="glyphicon glyphicon-menu-left" style="margin-right:10px;"></span>Voltar</a>

@endsection